name: CI for Android
# https://github.com/google/mozc/blob/master/docs/build_mozc_in_docker.md

# Run on push.
on: push

permissions: read-all

# Prevent previous workflows from running.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: setup
        run: |
          sudo apt-get update

      - name: build
        working-directory: ./src
        env:
          USE_BAZEL_VERSION: "8.0.0"
        run: |
          bazel build --config oss_android package --config release_build

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native_libs.zip
          path: src/bazel-bin/android/jni/native_libs.zip
          if-no-files-found: warn
