name: CI for macOS
# https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md

# Run on push.
on: push

# Prevent previous workflows from running.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-11
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: setup
        working-directory: ./src/third_party
        run: |
          # Install Packages for the packagesbuild command.
          wget http://s.sudre.free.fr/Software/files/Packages.dmg
          hdiutil attach Packages.dmg
          sudo installer -pkg /Volumes/Packages\ 1.2.10/Install\ Packages.pkg -target /
          #
          # Install Qt
          wget https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5152/qt.qt5.5152.clang_64/5.15.2-0-202011130601qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
          tar xf 5.15.2-0-202011130601qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
          #
          # MOZC_QT_PATH = "/(github_path)/mozc/src/third_party/5.15.2/clang_64"
          MOZC_QT_PATH=${PWD}/5.15.2/clang_64
          #
          # Change the default Android NDK version
          # https://github.com/actions/virtual-environments/issues/5595
          ANDROID_HOME=${HOME}/Library/Android/sdk
          ln -sfn ${ANDROID_HOME}/ndk/21.4.7075529 ${ANDROID_HOME}/ndk-bundle

      - name: build
        working-directory: ./src
        run: |
          bazel build --config oss_macos package

      - name: tests
        working-directory: ./src
        run: |
          bazel test --config oss_macos base/... mac/...
